name: Scrapper Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the tests
    - name: Run Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/

  run_script:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests run before this job

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the main script
    - name: Run the Script
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python src/main.py

    # Upload output files as artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-files
        path: |
          hockey_stats.zip
          hockey_stats.xlsx
